name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: chime-sps/sps-ops/.github/workflows/release.yml@main
    secrets: inherit
    with:
      event_repository: ${{ github.event.repository.name }}
