name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  precommit:
    uses: chime-sps/sps-ops/.github/workflows/precommit.yml@main
    secrets: inherit
  dispatch-tests:
    if: ${{github.event_name == 'push'}}
    uses: chime-sps/sps-ops/.github/workflows/dispatch-tests.yml@main
    secrets: inherit