name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: chime-sps/sps-ops/.github/workflows/release.yml@main
    secrets: inherit
    with:
      ref_name: ${{ github.ref_name || 'none' }}
      event_name: ${{ github.event_name || 'none'}}
      event_repository: ${{ github.event.repository.name || 'none' }}
